### ISSUE TITLE
Signing request for DynamoDB.

### ISSUE THREAD

**Issue by farazirfan47** [mfn/php-aws-post-v4-sign#1]
Could it work for signing requests for DynamoDB ?

**Comment by mfn** [comment]
I really can't say, I'm not a user of DynamoDB

**Comment by farazirfan47** [comment]
Ok, Thanks

**Comment by mfn** [comment]
Closing as I'm archiving the repo; I'm not using this code anymore (official aws php sdk caught up in the meantime, for me at least).
