### ISSUE TITLE
Getting error while installing from composer

### ISSUE THREAD

**Issue by saqlain-syed** [mfn/php-aws-post-v4-sign#2]
I have tried to install using composer.. but I am getting this error below.. I am using PHP 5.6 .. please help!

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package mfn/aws-post-v4-sign No version set (parsed as 1.0.0) is satisfiable by mfn/aws-post-v4-sign[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
>

**Comment by mfn** [comment]
Works for me:
```sh
~/tmp/test $ cat composer.json
{
    "name": "test/test",
    "require": {}
}
~/tmp/test $ composer.phar require mfn/aws-post-v4-sign
Using version ^0.1.0 for mfn/aws-post-v4-sign
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing mfn/aws-post-v4-sign (0.1): Downloading (100%)
Writing lock file
Generating autoload files
```
I would suggest to check your `composer.json`, specifically regarding `minimum-stability`.

If you can't solve it, please provide your `composer.json` and the actual command you tried to run.
